### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by ShadowManu** [mulderr/haskell-wamp#2]
Hi! I've been working on a game concept which requires some wamp-like stuff. Since its a personal project, I want to do it in haskell. What would you consider the status of the project? I would like to keep it going on ;)

**Comment by mulderr** [comment]
Hello! This was always meant to be an experiment and a fun exercise for me while learning Haskell. I haven't worked on this or used wamp really since 2015. I don't plan to either, at least not in the near future.

To repeat what I already wrote in #1, client basic profile should be mostly (?) complete unless there were some major changes in the spec. I never started work on the client advanced profile. Router implementation is by far the most experimental part of the code. I completely ignored ordering guarantees thinking I could maybe take this one step a time. Short story: nope. If you plan to do any work on the router I would definitely suggest to try and figure that out from the start. It seems it may be hard to retrofit a design to include ordering guarantees.

That said, if you would like to fork this and keep working on it then by all means go ahead :)

**Comment by ShadowManu** [comment]
Thanks for your answer. I've been considering writing an implementation of the protocol, and if I end up deciding in using wamp, I'll continue development.
